language: node_js
node_js:
  - "iojs"
branches:
  only:
    - master
    - "master-qa"
script:
  - echo "No Tests Yet!"
after_sucess: |
  BRANCH=$(git rev-parse --abbrev-ref HEAD)
  echo $BRANCH
  if [ $BRANCH == "master"] then
    npm run deploy-prod
  elif [ $BRANCH == "master-qa"] then
    npm run deploy-dev
  fi