language: node_js
node_js:
  - "iojs"
branches:
  only:
    - master
    - "master-qa"
script:
  - echo "No Tests Yet!"
after_success: |
  BRANCH=$(git rev-parse --abbrev-ref HEAD)
  echo $BRANCH
  if [ "$BRANCH" == "master" ]; then
    echo "prod"
  elif [ "$BRANCH" == "master-qa" ]; then
    echo "dev"
  fi