language: node_js
node_js:
  - "iojs"
branches:
  only:
    - master
    - "master-qa"
script:
  - echo "No Tests Yet!"

deploy:
  provider: script
  script: deploy.sh
  on:
  	branch: develop
  skip_cleanup: true