language: node_js
node_js:
  - "iojs"
  - "0.12"
branches:
  only:
    - master
    - master-qa
before_install:
  - npm install -g grunt-cli
install: NODE_ENV=development npm install
script:
  - echo "No Tests Yet!"
  - npm run deploy
  - bash deploy.sh
