language: node_js
node_js:
  - "iojs"
branches:
  only:
    - master
    - master-qa
before_install:
  - npm install -g grunt-cli
  - npm install grunt
install: NODE_ENV=development npm install
script:
  - echo "No Tests Yet!"
#  - grunt build
  - bash deploy.sh
