language: node_js
node_js:
  - "iojs"
branches:
  only:
    - master
    - "master-qa"
script:
  - echo "No Tests Yet!"
after_success: |
  echo $TRAVIS_BRANCH
  if [ "$TRAVIS_BRANCH" == "master" ]; then
    npm run deploy-prod
  elif [ "$TRAVIS_BRANCH" == "master-qa" ]; then
    npm run deploy-dev
  fi